### ISSUE TITLE
[NOTICE] pocketlang is trending I guess 🚀🎉🥳

### ISSUE THREAD

**Issue by xSavitar** [ThakeeNathees/pocketlang#110]
This is not really an issue but a notice that the repo is trending and stars are climbing up. Good job @ThakeeNathees and thanks for giving us an opportunity to be part of this journey.

Let's celebrate 😇  as it's now at 816 stars ⭐️

**Comment by ThakeeNathees** [comment]
Wow, that's a lot of stars for a day. I'm glad that many people find it worth staring.

Thanks everyone!

**Comment by tsujp** [comment]
I posted it on HackerNews: https://news.ycombinator.com/item?id=27588842

**Comment by ThakeeNathees** [comment]
@tsujp Thanks for spreading the word. And we're really glad you're here.

**Comment by ThakeeNathees** [comment]
Wow, pocketlang is at the top of today's trending 🎉 

![Screenshot (29)](https://user-images.githubusercontent.com/41085900/123312248-b02b0080-d545-11eb-9de8-0f8352b35e15.png)

@tsujp @xSavitar @alexcpatel

**Comment by xSavitar** [comment]
Yes it is, as it should be :)

Let's keep the work and PRs coming :)

**Comment by alexcpatel** [comment]
Oh wow, this is awesome!!

Going to take a look at open issues tonight,

**Comment by xSavitar** [comment]
We're almost hitting 1K stars. Will probably happen before tomorrow (UTC+01).

**Comment by ThakeeNathees** [comment]
@xSavitar Wow, We're at 1K. It's always a pleasure to collaborate with an enthusiastic contributor like you 🎉

**Comment by xSavitar** [comment]
This is exciting @ThakeeNathees. You're the one writing all the magic. Yes, pocketlang is growing gradually and I like it.
