### ISSUE TITLE
Map contains check (elem in map) implementation

### ISSUE THREAD

**Issue by ThakeeNathees** [ThakeeNathees/pocketlang#118]
We have `in` test after 64bf276 commit (ie. `elem in container`) however we currently only support lists, The map implementation would be fairly simple.

## How to implement
- You can find the TODO [here](https://github.com/ThakeeNathees/pocketlang/blob/64bf27674a068a008a78a545e7e353d5659dd1e9/src/pk_core.c#L1305)
- Use the [`mapGet()`](https://github.com/ThakeeNathees/pocketlang/blob/64bf27674a068a008a78a545e7e353d5659dd1e9/src/pk_var.h#L533-L535) function to check if the element exists.
- Return true if it exists.

## Finally

Don't forgot to write some tests at `tests/lang/basics.pk`
```ruby
assert('key' in {'key':'value'})
assert(!('foo' in {'bar':'baz'}))
```

**Comment by tsujp** [comment]
Created a PR: https://github.com/ThakeeNathees/pocketlang/pull/121
