### ISSUE TITLE
Include Nodejs in Benchmarks

### ISSUE THREAD

**Issue by lukeed** [ThakeeNathees/pocketlang#124]
Hey! It looks like you started implementing some JS for the benchmarks and stopped. There's a note in `loop.js` about V8's performance optimizations/benefits – I'm not sure if this deterred you from including/finishing JS or not, but I think it's still important to include them for context.

Pocketlang doesn't have to be the fastest in a graph in order for it to be considered :) It's a cool little language and I think it has more merit than speed.

I added the JS variants for all benchmarks and will include a sample of their results on my machine. Happy to PR the benchmark items if interested

```
Node v14.15.3
Python v3.9.5
Pocket (master : 6d434db) -> make release

benchmarks/fib
  node   0.090436s
  python 2.506929s
  pocket 1.380002s

benchmarks/list
  node   0.143674s
  python 2.351552s
  pocket 0.884381s

benchmarks/loop
  node   0.325279s
  python 1.946506s
  pocket 0.54898s

benchmarks/primes
  node   0.143707s
  python 2.6421330000000003s
  pocket 1.400831s
```

Again, I don't think this should be discouraging at all. It's amazing so far!

**Comment by ThakeeNathees** [comment]
In the developer's point of view, I was comparing similar implementations (bytecode interpreted) and it's unfair to compare with jit.

However, for a user, what's under the hood won't make much difference to them, guess js could be added to the benchmarks as well.

> Happy to PR the benchmark items if interested

I appreciate that you've taken your time to run all these benchmarks, and we're glad to have your PR, go ahead and open one.

**Comment by lukeed** [comment]
Yeah it's ultimately up to you, of course. It's a different tool for different use cases, but including Node (from a scripting lang PoV) can help reinforce what Pocketlang's (current) use cases/goals are.

Will send that PR :)

**Comment by ThakeeNathees** [comment]
This is resolved at #125

**Comment by lukeed** [comment]
#125 includes the candidates but I think results should still be displayed somewhere, as well as a message about your targeted use case for Pocketlang

**Comment by ThakeeNathees** [comment]
@lukeed The docs are still in WIP, these benchmarks would go there.
