### ISSUE TITLE
Add `log` function to pocketlang math module

### ISSUE THREAD

**Issue by ThakeeNathees** [ThakeeNathees/pocketlang#155]
Currently, our math module isn't completely filled with necessary math functions, where you can contribute us by adding more math functions. This issue has reference on how to add `log` function to the math module.

### How to implement
PR #154 has example on how to add `log10` to the math module, which you can use as a reference to add `log` (base 2) function.

### Finally
And don't forget to add some tests to `tests/lang/core.pk`.

**Comment by emersonlaurentino** [comment]
@ThakeeNathees this issue must be closed, as pr #160 resolves this.
