### ISSUE TITLE
[Question] What is the intended way to pass variables between C and Pocketlang?

### ISSUE THREAD

**Issue by billy4479** [ThakeeNathees/pocketlang#156]
I was playing around with Pocketlang and it looks really cool!
This is my first time using an embedded language and I got stuck when I had to read a global variable from my script and use it in C.

My solution was creating a native function that will have to be called from the script using the variable as argument. Something like this:
```python
a = 10
variableToC(a)
```

I ran into a similar issue when I had to set a global variable from C. I saw that `pkModuleAddGlobal` exists but I wasn't able to create a `*PkHandle` from, for example, an int.
I also was able to solve this using native functions and returning the value I wanted.

Are those the intended ways?
I think it would be cool if it was a more straight forward way, something like `*PkHandle pkCreateNumber(PKVM* vm, const char* name, double value)` for creating new variables and something like `bool pkGetGlobalNumber(PKVM* vm, const char* name, double* value)` to get a value from the VM.

I saw [here](https://github.com/ThakeeNathees/pocketlang/blob/master/src/include/pocketlang.h#L446) that creating variables is in the TODO list. Are we refering to the same thing?
As I said, this is my first time working with embedded languages so it's possible that I'm doing something wrong.

**Comment by ThakeeNathees** [comment]
> I also was able to solve this using native functions and returning the value I wanted.
Are those the intended ways?

Currently, yes.

I've made a simplified example on how to pass values between pocket and C below.
Just copy it as `test.c` and place the `src/` folder next to the `test.c` file and compile using the below command.

```
gcc -o test test.c src/*.c -Isrc/include -lm
```

```C

#include <pocketlang.h>
#include <stdio.h>

// The pocket script.
static const char* code = ""
  "  from YourModule import variableToC \n"
  "  a = 10                             \n"
  "  b = variableToC(a)                 \n"
  "  print('[pocket] b =', b)           \n"
  ;

/*****************************************************************************/
/* MODULE FUNCTION                                                           */
/*****************************************************************************/

static void variableToC(PKVM* vm) {
  
  // Get the parameter from pocket VM.
  double a;
  if (!pkGetArgNumber(vm, 1, &a)) return;
  
  printf("[C] a = %f\n",a);
  
  // Return value to the pocket VM.
  pkReturnNumber(vm, 3.14);
}

/*****************************************************************************/
/* POCKET VM CALLBACKS                                                       */
/*****************************************************************************/

// Error report callback.
static void reportError(PKVM* vm, PkErrorType type,
                        const char* file, int line,
                        const char* message) {
  fprintf(stderr, "Error: %s\n", message);
}

// print() callback to write stdout.
static void stdoutWrite(PKVM* vm, const char* text) {
  fprintf(stdout, "%s", text);
}

/*****************************************************************************/
/* MAIN                                                                      */
/*****************************************************************************/

int main(int argc, char** argv) {

  // Pocket VM configuration.
  PkConfiguration config = pkNewConfiguration();
  config.error_fn  = reportError;
  config.write_fn  = stdoutWrite;
  //config.read_fn = stdinRead;

  // Create a new pocket VM.
  PKVM* vm = pkNewVM(&config);
  
  // Register your module.
  PkHandle* your_module = pkNewModule(vm, "YourModule");
  pkModuleAddFunction(vm, your_module, "variableToC",  variableToC, 1);
  pkReleaseHandle(vm, your_module);
  
  // The path and the source code.
  PkStringPtr source = { code, NULL, NULL, 0, 0 };
  PkStringPtr path = { "./some/path/", NULL, NULL, 0, 0 };
  
  // Run the code.
  PkResult result = pkInterpretSource(vm, source, path, NULL/*options*/);
  
  // Free the VM.
  pkFreeVM(vm);
  
  return (int)result;
}
```

#### The output

```
[C] a = 10.000000
[pocket] b = 3.14
```

----

Currently, you can't directly change the global values (TODO). However, you can add a new global variable once you created a module with the API `pkNewModule(...)`. And you can create a handle to a variable using `pkNew...()` function (ex: `pkNewString(vm, "foo")`), But It doesn't support primitive, non heap allocated (and non garbage collected) types yet because that could be done by some other memory efficient way. 

> I saw here that creating variables is in the TODO list. Are we refering to the same thing?

Yes, Im thinking about a primitive (non garbage collected) variable buffer (or a fixed size array) to store them and make the handle points to the variable in that buffer, this will prevent us from invoking an allocation call for each time we want to pass a primitive type.

----

@billy4479 If you have any questions or suggestions let me know.

**Comment by billy4479** [comment]
Thanks for the clarification! Keep it up!
