### ISSUE TITLE
allow pocketlang to be compiled in linux

### ISSUE THREAD

**Issue by masrourmouad** [ThakeeNathees/pocketlang#23]
allow pocketlang to be compiled in linux

**Comment by masrourmouad** [comment]
gfus

**Comment by ThakeeNathees** [comment]
For the records, pocketlang was always been supported to be compiled in linux but it wasn't documented as it's currently at the pre-alpha stage. Here is how to compile for linux.

```
gcc -o pocket cli/*.c src/*.c -Isrc/include -lm -Wno-int-to-pointer-cast
```

**And with that attitude, you're not welcome here.**
