### ISSUE TITLE
[RfC] Extract FIXME/TODO from codebase that's beginner fiendly

### ISSUE THREAD

**Issue by xSavitar** [ThakeeNathees/pocketlang#53]
@ThakeeNathees, could you curate a couple of beginner friend tasks from the codebase's FIXME or TODO sections? This is so that I can begin making code-wise contributions in a direction that makes sense rather than just attempting to make some changes etc.

From your view point, I think a couple of issues that I can start with will be awesome. Let me know if this is something you'll like to do so I can begin giving you assistance. Thank you!

**Comment by ThakeeNathees** [comment]
It's a good idea to have some beginner-friendly tasks, I'm thinking about opening some [![](https://img.shields.io/github/labels/thakeenathees/pocketlang/good%20first%20issue)](https://github.com/ThakeeNathees/pocketlang/labels/good%20first%20issue) labeled issue for TODOs explaining the issue with pointers on how to solve it.

And sool I'll write an [architectural overview](https://www.ibm.com/docs/en/SSXPJK_6.0.3/com.ibm.aps.install.doc/graphics/Architecture.jpg) explaining about how pocketlang (and other bytecode interpreted languages) works under the hood (I too started this project to learn about programming languages). Which you may find useful to understand the compiler concepts and get started with the pocketlang internals.

**Comment by xSavitar** [comment]
Yes @ThakeeNathees. Awesome  though on starting the `good first issue` tasks. I'll start with those. And I agree with you that this project will be a good way to understand about programming languages in general (be it compiled or interpreted), how compilers work etc.

Thanks for starting this project and I'm glad I found it when it was still in its early phase so I can contribute :)

**Comment by xSavitar** [comment]
I'll go ahead and close this now! Thanks for considering the idea @ThakeeNathees :)
