### ISSUE TITLE
Add start, end attribute to range

### ISSUE THREAD

**Issue by ThakeeNathees** [ThakeeNathees/pocketlang#60]
Currently there is no way of getting the start and end value of a range object
```
>>> r = 1..100
[Range:1..100]
>>> r.start
Error: 'Range' object has no attribute named 'start'
  $(SourceBody)() [line:1]
>>>
```
In the above, it's expected to print `1` for the `.start` attribute

## How to implement

- [Here](https://github.com/ThakeeNathees/pocketlang/blob/473daa4716bcccf58add33d8f952665a90bf9411/src/pk_core.c#L1232-L1246) is the switch statement that matches the attribute name and returns its value.
```c
    case OBJ_RANGE:
    {
      Range* range = (Range*)obj;
      SWITCH_ATTRIB(attrib->data) {

        CASE_ATTRIB("as_list", 0x1562c22) :
          return VAR_OBJ(rangeAsList(vm, range));

        default:
          ERR_NO_ATTRIB(vm, on, attrib);
          return VAR_NULL;
      }

      UNREACHABLE();
    }
```
- Add attrib with the name `"start"` and `"end"`, (their corresponding values are `range->from` and `range->to`) the second argument of the `CASE_ATTRIB` macro is the hash value of the string, which you can get like this.
```
>>> from math import hash
>>> print(hex(hash("as_list")))
0x1562c22
>>>
```

**Comment by xSavitar** [comment]
@ThakeeNathees, there seems to be a problem using `end` for constructing the `.end` attribute. I've tried it and it doesn't work. Maybe it's due to the "end" keyword?

**Comment by ThakeeNathees** [comment]
@xSavitar Ooh, I didn't realize `end` is reserved, it's okey I've renamed them to `first` and `last`

**Comment by xSavitar** [comment]
Oh perfect! I see this now. Thanks :)
