### ISSUE TITLE
Rename elif to elsif

### ISSUE THREAD

**Issue by ThakeeNathees** [ThakeeNathees/pocketlang#74]
## Discussion

Currently, our "else if keyword" is `elif` which something I've derived from python, however

- Our language syntactically very much like ruby, and it would confuse the users (especially those who have a ruby background) and it's like learning a new language (since `elsif` is the ruby's way).
- On the other hand, if someone learned pocketlang, it would be easier for them to continue with ruby (so we'll keep it as closer to ruby as possible).
- We can also reuse any of ruby's syntax highlighter if we ever have to use one.
- Reading `elsif` sounds more like `else if` then `elif` does.

If you have any suggestions, regarding the renaming let me know.

## How to rename

- the name is defined at `src/pk_compiler.c` ([here is the line](https://github.com/ThakeeNathees/pocketlang/blob/c58159b63d5565a4788e300f5fb4e964b8d0c6d5/src/pk_compiler.c#L193))
- just renaming `"elif"` to `"elsif"` is sufficient but for consistency rename, it's token name from `TK_ELIF` to `TK_ELSIF` and find `elif` in the comments if any and replace them too.

**Comment by ThakeeNathees** [comment]
#### CC @xSavitar @alexcpatel

**Comment by xSavitar** [comment]
I think the `elsif` one reads more like `else if` but however it could be typed the full way: `elseif` by mistake. Thinking deeper, this typos can be introduced even for `elif` as well.

I support the renaming in this case :)

**Comment by ThakeeNathees** [comment]
The goal of this renaming is to reduce the potential typos, the ruby users tend to use `elsif` then `elif` and having a grammar that matches a mainstream language would make users not learn a new language.

Also if someone left a typo for `elsif` it wont live longer than a [nightly build](https://softwareengineering.stackexchange.com/questions/56490/what-does-nightly-builds-mean). The parser won't accept a misspelled keyword.

**Comment by ThakeeNathees** [comment]
Fixed by: #75
