### ISSUE TITLE
Move fiber functions into its own module

### ISSUE THREAD

**Issue by ThakeeNathees** [ThakeeNathees/pocketlang#89]
Pocketlang support co-routine via [fibers](https://thakeenathees.github.io/pocketlang/language-api-fibers.html). The functions to create and interact with fibers are builtin functions (see [here](https://github.com/ThakeeNathees/pocketlang/blob/1e6fd9de5ef0f45bfe8a4aab6c166dd590ea3e08/src/pk_core.c#L996-L1001))
This needs to be moved into its own module named `Fiber` to organize everything and have a clean interface.

#### This is the current fiber interface.
```ruby
fb = fiber_new(fn)  ## creating a fiber
fiber_run(fb, args...) ## start running
fiber_resume(fb, val) ## resume once yielded
fiber_is_done(fb) ## check if it's done
fiber_get_func(fb) ## get the underlying function
```

#### They need to be refactored in to
```ruby
import Fiber
fb = Fiber.new(fn)  ## creating a fiber
Fiber.run(fb, args...) ## start running
Fiber.resume(fb, val) ## resume once yielded
fb.is_done ## check if it's done
fb.function ## get the underlying function 
```

## How to implement

- This is how the math module is defined use it as a reference (see [here](https://github.com/ThakeeNathees/pocketlang/blob/1e6fd9de5ef0f45bfe8a4aab6c166dd590ea3e08/src/pk_core.c#L1014-L1024))
```c
Script* math = newModuleInternal(vm, "math");
moduleAddFunctionInternal(vm, math, "floor", stdMathFloor,   1);
moduleAddFunctionInternal(vm, math, "ceil",  stdMathCeil,    1);
```
- Create a `Fiber` module and add it's functions (just below math module) (you have to rename `coreFiberNew` to `stdFiberNew` to indicate it's a module function and not a builtin function)
```c
Script* Fiber = newModuleInternal(vm, "Fiber");
moduleAddFunctionInternal(vm, Fiber, "new", stdFiberNew,    1);
moduleAddFunctionInternal(vm, Fiber, "run", stdFiberRun,   -1);
```

- Remove the `coreFiberIsDone` and `coreFiberGetFunc` functions, because we're changing them to fiber attributes. (delete [these lines](https://github.com/ThakeeNathees/pocketlang/blob/1e6fd9de5ef0f45bfe8a4aab6c166dd590ea3e08/src/pk_core.c#L638-L655))

- Now add `"is_done"` and `"function"` attribute to fibers ([here](https://github.com/ThakeeNathees/pocketlang/blob/1e6fd9de5ef0f45bfe8a4aab6c166dd590ea3e08/src/pk_core.c#L1399)). replace the `???` with the name's hash value (see below). (use `coreFiberIsDone` and `coreFiberGetFunc` for the return value here)
```c
  case OBJ_FIBER:
    {
      Fiber* fb = (Fiber*)obj;
      SWITCH_ATTRIB(attrib->data) {

        CASE_ATTRIB("is_done", ???) :
          // TODO: return is done

        CASE_ATTRIB("function", ???) :
          // TODO: return function

      CASE_DEFAULT:
        ERR_NO_ATTRIB(vm, on, attrib);
        return VAR_NULL;
      }
      UNREACHABLE();
    }
```
The second argument of the `CASE_ATTRIB` macro is the hash value of the string, which you can get like this. (run the pocket lang from the command line and evaluate this or you could you [this python function](https://github.com/ThakeeNathees/pocketlang/blob/1e6fd9de5ef0f45bfe8a4aab6c166dd590ea3e08/tests/check.py#L109-L120))
```
>>> from math import hash
>>> print(hex(hash("foo")))
0xa9f37ed7
>>>
```

### Finally

Make sure everything works fine by running the unit test script at `tests/tests.py` and run the `tests/check.py` to check if the hash value matches the string.

**Comment by TiagoCavalcante** [comment]
@ThakeeNathees shouldn't both start with a uppercase or lowercase letter?

It's confusing to one of the main modules start with a uppercase letter and other with a lowercase letter.

**Comment by ThakeeNathees** [comment]
@TiagoCavalcanteTrindade It's because the `math` module is a collection of functions but `Fiber` is an object wrapper (which you can use as a type) Similar for `path` - collection of path functions, but `File` a file object wrapper library. If you have any suggestions feel free to discuss.
