### ISSUE TITLE
Update the copyright statement in the source files.

### ISSUE THREAD

**Issue by ThakeeNathees** [ThakeeNathees/pocketlang#92]
The current copyright statement in the file headers doesn't address the [pocketlang aurhtos](https://github.com/ThakeeNathees/pocketlang/blob/master/AUTHORS). It should be updated like this.

### Before
```
/*
 *  Copyright (c) 2020-2021 Thakee Nathees
 *  Distributed Under The MIT License
 */
```

### After
```
/*
 *  Copyright (c) 2020-2021 Thakee Nathees
 *  Copyright (c) 2021 The pocketlang Authors
 *  Distributed Under The MIT License
 */
```

And thanks for being part of this :tada:

**Comment by ThakeeNathees** [comment]
CC @xSavitar @alexcpatel

**Comment by xSavitar** [comment]
Sounds like a good idea. Maybe something like: `Copyright (c) 2021 The pocketlang team` ;]

**Comment by ThakeeNathees** [comment]
> Sounds like a good idea. Maybe something like: Copyright (c) 2021 The pocketlang team ;]

I'm not sure about that, here are some conventional way:  https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code#what-if-there-are-many-authors-or-copyright-is-held-by-a-legal-entity

**Comment by xSavitar** [comment]
Okay nice! In that case, then this format makes more sense to me:

`© 1998 Contributors to the Project X <https://git.projectx.example/ProjectX/blob/master/CONTRIBUTORS.markdown>`

**Comment by ThakeeNathees** [comment]
@xSavitar Isn't it too lengthy, we're trying to keep it at maximum 79 characters per line.
```
/*
 *  Copyright (c) 2020-2021 Thakee Nathees
 *  Copyright (c) 2021 Contributors to the Project pocketlang <https://github.com/ThakeeNathees/pocketlang/blob/master/AUTHORS>
 *  Distributed Under The MIT License
 */
```

**Comment by xSavitar** [comment]
The URL makes it really lengthy. I'll check out other alternatives and share :)

**Comment by ThakeeNathees** [comment]
Closing as I'd like to do it myself, and again thanks!
