### ISSUE TITLE
Parse command line args

### ISSUE THREAD

**Issue by ThakeeNathees** [ThakeeNathees/pocketlang#99]
We don't have an argparser for the command line yet, which you could help us to implement.  It would be easier to use a small (preferred single heder or a maximum of 2 source files) library than writing one yourself from scratch. 

https://github.com/cofyc/argparse seems good to me (I haven't used or tested it before), or something else you know might be great, but for License compatibility, we're only using MIT licensed or public domain libraries in pocketlang.

Here is an expected example usage message (feel free to come up with your own one).

```
usage: pocket [option] ... [-c cmd | file | -] [arg] ...
  -c cmd          Evaluate and run the passed string.
  -d, --debug     Compile and run a debug version.
  -h, --help      Prints this help message and exit.
  -q, --quiet     Don't print version and copyright statement on REPL startup
  -v, --version   Prints the pocketlang version number and exit.
```

**Comment by ThakeeNathees** [comment]
CC @xSavitar

**Comment by xSavitar** [comment]
Part 1 of the argparse will be coming soon. I used the repo you suggested as a submodule to our repo. In addition, it's in the `thirdparty` subdirectory of the `cli/` directory. So you'll need to run `git submodule update` to fetch it down.

**Comment by ThakeeNathees** [comment]
Great, but adding a submodule requires someone to perform a  recursive clone, one of our goals here is **simplicity**. Adding submodules breaks that. We never should add a submodule.

I'd like it to be added like other third-party libraries (see cwalk). Copy only the source files and the license (`argparse.c`, `argparse.h`, `ICENSE`)

And don't forget to include the `argparse.c` in the `thirdparty.c`
> thirdparty.c
// This file will include all thirdparty source files from the thirdparty sub
// directories here into a single file. That'll make it easy to compile with
// the command `gcc cli/*.c ...` instead of having to add every single sub
// directory to the list of source directory.

**Comment by xSavitar** [comment]
Makes sense! Thank you!
